# Generated by Django 4.2.7 on 2026-01-24 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
